/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bankito.persistencia.jdbc;

import com.bankito.persistencia.dao.*;
import com.bankito.persistencia.factory.*;
import com.bankito.persistencia.dto.*;
import com.bankito.persistencia.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class PerfilUsuarioEntidadDaoImpl extends AbstractDAO implements PerfilUsuarioEntidadDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT id_perfil_usuario, nombre, descripcion FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( id_perfil_usuario, nombre, descripcion ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET id_perfil_usuario = ?, nombre = ?, descripcion = ? WHERE id_perfil_usuario = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE id_perfil_usuario = ?";

	/** 
	 * Index of column id_perfil_usuario
	 */
	protected static final int COLUMN_ID_PERFIL_USUARIO = 1;

	/** 
	 * Index of column nombre
	 */
	protected static final int COLUMN_NOMBRE = 2;

	/** 
	 * Index of column descripcion
	 */
	protected static final int COLUMN_DESCRIPCION = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column id_perfil_usuario
	 */
	protected static final int PK_COLUMN_ID_PERFIL_USUARIO = 1;

	/** 
	 * Inserts a new row in the perfil_usuario table.
	 */
	public PerfilUsuarioEntidadPk insert(PerfilUsuarioEntidad dto) throws PerfilUsuarioEntidadDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdPerfilUsuarioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "id_perfil_usuario" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isNombreModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "nombre" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isDescripcionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "descripcion" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString(), Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			if (dto.isIdPerfilUsuarioModified()) {
				stmt.setInt( index++, dto.getIdPerfilUsuario() );
			}
		
			if (dto.isNombreModified()) {
				stmt.setString( index++, dto.getNombre() );
			}
		
			if (dto.isDescripcionModified()) {
				stmt.setString( index++, dto.getDescripcion() );
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdPerfilUsuario( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			throw new PerfilUsuarioEntidadDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the perfil_usuario table.
	 */
	public void update(PerfilUsuarioEntidadPk pk, PerfilUsuarioEntidad dto) throws PerfilUsuarioEntidadDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdPerfilUsuario() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setString( index++, dto.getDescripcion() );
			stmt.setInt( 4, pk.getIdPerfilUsuario() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
		}
		catch (Exception _e) {
			throw new PerfilUsuarioEntidadDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the perfil_usuario table.
	 */
	public void delete(PerfilUsuarioEntidadPk pk) throws PerfilUsuarioEntidadDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdPerfilUsuario() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
		}
		catch (Exception _e) {
			throw new PerfilUsuarioEntidadDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the perfil_usuario table that matches the specified primary-key value.
	 */
	public PerfilUsuarioEntidad findByPrimaryKey(PerfilUsuarioEntidadPk pk) throws PerfilUsuarioEntidadDaoException
	{
		return findByPrimaryKey( pk.getIdPerfilUsuario() );
	}

	/** 
	 * Returns all rows from the perfil_usuario table that match the criteria 'id_perfil_usuario = :idPerfilUsuario'.
	 */
	public PerfilUsuarioEntidad findByPrimaryKey(int idPerfilUsuario) throws PerfilUsuarioEntidadDaoException
	{
		PerfilUsuarioEntidad ret[] = findByDynamicSelect( SQL_SELECT + " WHERE id_perfil_usuario = ?", new Object[] {  new Integer(idPerfilUsuario) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the perfil_usuario table that match the criteria ''.
	 */
	public PerfilUsuarioEntidad[] findAll() throws PerfilUsuarioEntidadDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY id_perfil_usuario", null );
	}

	/** 
	 * Returns all rows from the perfil_usuario table that match the criteria 'id_perfil_usuario = :idPerfilUsuario'.
	 */
	public PerfilUsuarioEntidad[] findWhereIdPerfilUsuarioEquals(int idPerfilUsuario) throws PerfilUsuarioEntidadDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id_perfil_usuario = ? ORDER BY id_perfil_usuario", new Object[] {  new Integer(idPerfilUsuario) } );
	}

	/** 
	 * Returns all rows from the perfil_usuario table that match the criteria 'nombre = :nombre'.
	 */
	public PerfilUsuarioEntidad[] findWhereNombreEquals(String nombre) throws PerfilUsuarioEntidadDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE nombre = ? ORDER BY nombre", new Object[] { nombre } );
	}

	/** 
	 * Returns all rows from the perfil_usuario table that match the criteria 'descripcion = :descripcion'.
	 */
	public PerfilUsuarioEntidad[] findWhereDescripcionEquals(String descripcion) throws PerfilUsuarioEntidadDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE descripcion = ? ORDER BY descripcion", new Object[] { descripcion } );
	}

	/**
	 * Method 'PerfilUsuarioEntidadDaoImpl'
	 * 
	 */
	public PerfilUsuarioEntidadDaoImpl()
	{
	}

	/**
	 * Method 'PerfilUsuarioEntidadDaoImpl'
	 * 
	 * @param userConn
	 */
	public PerfilUsuarioEntidadDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "bankito.perfil_usuario";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected PerfilUsuarioEntidad fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			PerfilUsuarioEntidad dto = new PerfilUsuarioEntidad();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected PerfilUsuarioEntidad[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			PerfilUsuarioEntidad dto = new PerfilUsuarioEntidad();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		PerfilUsuarioEntidad ret[] = new PerfilUsuarioEntidad[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(PerfilUsuarioEntidad dto, ResultSet rs) throws SQLException
	{
		dto.setIdPerfilUsuario( rs.getInt( COLUMN_ID_PERFIL_USUARIO ) );
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
		dto.setDescripcion( rs.getString( COLUMN_DESCRIPCION ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(PerfilUsuarioEntidad dto)
	{
		dto.setIdPerfilUsuarioModified( false );
		dto.setNombreModified( false );
		dto.setDescripcionModified( false );
	}

	/** 
	 * Returns all rows from the perfil_usuario table that match the specified arbitrary SQL statement
	 */
	public PerfilUsuarioEntidad[] findByDynamicSelect(String sql, Object[] sqlParams) throws PerfilUsuarioEntidadDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			throw new PerfilUsuarioEntidadDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the perfil_usuario table that match the specified arbitrary SQL statement
	 */
	public PerfilUsuarioEntidad[] findByDynamicWhere(String sql, Object[] sqlParams) throws PerfilUsuarioEntidadDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			throw new PerfilUsuarioEntidadDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
