/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bankito.persistencia.jdbc;

import com.bankito.persistencia.dao.*;
import com.bankito.persistencia.factory.*;
import com.bankito.persistencia.dto.*;
import com.bankito.persistencia.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class PerfilUsuarioOperacionEntidadDaoImpl extends AbstractDAO implements PerfilUsuarioOperacionEntidadDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT perfil_usuario_id_perfil, operacion_id_operacion FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( perfil_usuario_id_perfil, operacion_id_operacion ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET perfil_usuario_id_perfil = ?, operacion_id_operacion = ? WHERE perfil_usuario_id_perfil = ? AND operacion_id_operacion = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE perfil_usuario_id_perfil = ? AND operacion_id_operacion = ?";

	/** 
	 * Index of column perfil_usuario_id_perfil
	 */
	protected static final int COLUMN_PERFIL_USUARIO_ID_PERFIL = 1;

	/** 
	 * Index of column operacion_id_operacion
	 */
	protected static final int COLUMN_OPERACION_ID_OPERACION = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column perfil_usuario_id_perfil
	 */
	protected static final int PK_COLUMN_PERFIL_USUARIO_ID_PERFIL = 1;

	/** 
	 * Index of primary-key column operacion_id_operacion
	 */
	protected static final int PK_COLUMN_OPERACION_ID_OPERACION = 2;

	/** 
	 * Inserts a new row in the perfil_usuario_operacion table.
	 */
	public PerfilUsuarioOperacionEntidadPk insert(PerfilUsuarioOperacionEntidad dto) throws PerfilUsuarioOperacionEntidadDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isPerfilUsuarioIdPerfilModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "perfil_usuario_id_perfil" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isOperacionIdOperacionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "operacion_id_operacion" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isPerfilUsuarioIdPerfilModified()) {
				stmt.setInt( index++, dto.getPerfilUsuarioIdPerfil() );
			}
		
			if (dto.isOperacionIdOperacionModified()) {
				stmt.setInt( index++, dto.getOperacionIdOperacion() );
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			throw new PerfilUsuarioOperacionEntidadDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the perfil_usuario_operacion table.
	 */
	public void update(PerfilUsuarioOperacionEntidadPk pk, PerfilUsuarioOperacionEntidad dto) throws PerfilUsuarioOperacionEntidadDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getPerfilUsuarioIdPerfil() );
			stmt.setInt( index++, dto.getOperacionIdOperacion() );
			stmt.setInt( 3, pk.getPerfilUsuarioIdPerfil() );
			stmt.setInt( 4, pk.getOperacionIdOperacion() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
		}
		catch (Exception _e) {
			throw new PerfilUsuarioOperacionEntidadDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the perfil_usuario_operacion table.
	 */
	public void delete(PerfilUsuarioOperacionEntidadPk pk) throws PerfilUsuarioOperacionEntidadDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getPerfilUsuarioIdPerfil() );
			stmt.setInt( 2, pk.getOperacionIdOperacion() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
		}
		catch (Exception _e) {
			throw new PerfilUsuarioOperacionEntidadDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the perfil_usuario_operacion table that matches the specified primary-key value.
	 */
	public PerfilUsuarioOperacionEntidad findByPrimaryKey(PerfilUsuarioOperacionEntidadPk pk) throws PerfilUsuarioOperacionEntidadDaoException
	{
		return findByPrimaryKey( pk.getPerfilUsuarioIdPerfil(), pk.getOperacionIdOperacion() );
	}

	/** 
	 * Returns all rows from the perfil_usuario_operacion table that match the criteria 'perfil_usuario_id_perfil = :perfilUsuarioIdPerfil AND operacion_id_operacion = :operacionIdOperacion'.
	 */
	public PerfilUsuarioOperacionEntidad findByPrimaryKey(int perfilUsuarioIdPerfil, int operacionIdOperacion) throws PerfilUsuarioOperacionEntidadDaoException
	{
		PerfilUsuarioOperacionEntidad ret[] = findByDynamicSelect( SQL_SELECT + " WHERE perfil_usuario_id_perfil = ? AND operacion_id_operacion = ?", new Object[] {  new Integer(perfilUsuarioIdPerfil),  new Integer(operacionIdOperacion) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the perfil_usuario_operacion table that match the criteria ''.
	 */
	public PerfilUsuarioOperacionEntidad[] findAll() throws PerfilUsuarioOperacionEntidadDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY perfil_usuario_id_perfil, operacion_id_operacion", null );
	}

	/** 
	 * Returns all rows from the perfil_usuario_operacion table that match the criteria 'operacion_id_operacion = :operacionIdOperacion'.
	 */
	public PerfilUsuarioOperacionEntidad[] findByOperacion(int operacionIdOperacion) throws PerfilUsuarioOperacionEntidadDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE operacion_id_operacion = ?", new Object[] {  new Integer(operacionIdOperacion) } );
	}

	/** 
	 * Returns all rows from the perfil_usuario_operacion table that match the criteria 'perfil_usuario_id_perfil = :perfilUsuarioIdPerfil'.
	 */
	public PerfilUsuarioOperacionEntidad[] findByPerfilUsuario(int perfilUsuarioIdPerfil) throws PerfilUsuarioOperacionEntidadDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE perfil_usuario_id_perfil = ?", new Object[] {  new Integer(perfilUsuarioIdPerfil) } );
	}

	/** 
	 * Returns all rows from the perfil_usuario_operacion table that match the criteria 'perfil_usuario_id_perfil = :perfilUsuarioIdPerfil'.
	 */
	public PerfilUsuarioOperacionEntidad[] findWherePerfilUsuarioIdPerfilEquals(int perfilUsuarioIdPerfil) throws PerfilUsuarioOperacionEntidadDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE perfil_usuario_id_perfil = ? ORDER BY perfil_usuario_id_perfil", new Object[] {  new Integer(perfilUsuarioIdPerfil) } );
	}

	/** 
	 * Returns all rows from the perfil_usuario_operacion table that match the criteria 'operacion_id_operacion = :operacionIdOperacion'.
	 */
	public PerfilUsuarioOperacionEntidad[] findWhereOperacionIdOperacionEquals(int operacionIdOperacion) throws PerfilUsuarioOperacionEntidadDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE operacion_id_operacion = ? ORDER BY operacion_id_operacion", new Object[] {  new Integer(operacionIdOperacion) } );
	}

	/**
	 * Method 'PerfilUsuarioOperacionEntidadDaoImpl'
	 * 
	 */
	public PerfilUsuarioOperacionEntidadDaoImpl()
	{
	}

	/**
	 * Method 'PerfilUsuarioOperacionEntidadDaoImpl'
	 * 
	 * @param userConn
	 */
	public PerfilUsuarioOperacionEntidadDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "bankito.perfil_usuario_operacion";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected PerfilUsuarioOperacionEntidad fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			PerfilUsuarioOperacionEntidad dto = new PerfilUsuarioOperacionEntidad();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected PerfilUsuarioOperacionEntidad[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			PerfilUsuarioOperacionEntidad dto = new PerfilUsuarioOperacionEntidad();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		PerfilUsuarioOperacionEntidad ret[] = new PerfilUsuarioOperacionEntidad[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(PerfilUsuarioOperacionEntidad dto, ResultSet rs) throws SQLException
	{
		dto.setPerfilUsuarioIdPerfil( rs.getInt( COLUMN_PERFIL_USUARIO_ID_PERFIL ) );
		dto.setOperacionIdOperacion( rs.getInt( COLUMN_OPERACION_ID_OPERACION ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(PerfilUsuarioOperacionEntidad dto)
	{
		dto.setPerfilUsuarioIdPerfilModified( false );
		dto.setOperacionIdOperacionModified( false );
	}

	/** 
	 * Returns all rows from the perfil_usuario_operacion table that match the specified arbitrary SQL statement
	 */
	public PerfilUsuarioOperacionEntidad[] findByDynamicSelect(String sql, Object[] sqlParams) throws PerfilUsuarioOperacionEntidadDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			throw new PerfilUsuarioOperacionEntidadDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the perfil_usuario_operacion table that match the specified arbitrary SQL statement
	 */
	public PerfilUsuarioOperacionEntidad[] findByDynamicWhere(String sql, Object[] sqlParams) throws PerfilUsuarioOperacionEntidadDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			throw new PerfilUsuarioOperacionEntidadDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
