/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bankito.persistencia.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the cliente table.
 */
public class ClienteEntidadPk implements Serializable
{
	protected int idCliente;

	/** 
	 * This attribute represents whether the primitive attribute idCliente is null.
	 */
	protected boolean idClienteNull;

	/** 
	 * Sets the value of idCliente
	 */
	public void setIdCliente(int idCliente)
	{
		this.idCliente = idCliente;
	}

	/** 
	 * Gets the value of idCliente
	 */
	public int getIdCliente()
	{
		return idCliente;
	}

	/**
	 * Method 'ClienteEntidadPk'
	 * 
	 */
	public ClienteEntidadPk()
	{
	}

	/**
	 * Method 'ClienteEntidadPk'
	 * 
	 * @param idCliente
	 */
	public ClienteEntidadPk(final int idCliente)
	{
		this.idCliente = idCliente;
	}

	/** 
	 * Sets the value of idClienteNull
	 */
	public void setIdClienteNull(boolean idClienteNull)
	{
		this.idClienteNull = idClienteNull;
	}

	/** 
	 * Gets the value of idClienteNull
	 */
	public boolean isIdClienteNull()
	{
		return idClienteNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ClienteEntidadPk)) {
			return false;
		}
		
		final ClienteEntidadPk _cast = (ClienteEntidadPk) _other;
		if (idCliente != _cast.idCliente) {
			return false;
		}
		
		if (idClienteNull != _cast.idClienteNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idCliente;
		_hashCode = 29 * _hashCode + (idClienteNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.bankito.persistencia.dto.ClienteEntidadPk: " );
		ret.append( "idCliente=" + idCliente );
		return ret.toString();
	}

}
