/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bankito.persistencia.dto;

import com.bankito.persistencia.dao.*;
import com.bankito.persistencia.factory.*;
import com.bankito.persistencia.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class CuentaEntidad implements Serializable
{
	/** 
	 * This attribute maps to the column id_cuenta in the cuenta table.
	 */
	protected int idCuenta;

	/** 
	 * This attribute maps to the column num_entidad in the cuenta table.
	 */
	protected int numEntidad;

	/** 
	 * This attribute maps to the column num_sucursal in the cuenta table.
	 */
	protected int numSucursal;

	/** 
	 * This attribute maps to the column num_digito_control in the cuenta table.
	 */
	protected int numDigitoControl;

	/** 
	 * This attribute maps to the column num_cuenta in the cuenta table.
	 */
	protected long numCuenta;

	/** 
	 * This attribute maps to the column saldo in the cuenta table.
	 */
	protected float saldo;

	/** 
	 * This attribute maps to the column fecha_creacion in the cuenta table.
	 */
	protected Date fechaCreacion;

	/** 
	 * This attribute maps to the column usuario_id_usuario in the cuenta table.
	 */
	protected int usuarioIdUsuario;

	/**
	 * Method 'CuentaEntidad'
	 * 
	 */
	public CuentaEntidad()
	{
	}

	/**
	 * Method 'getIdCuenta'
	 * 
	 * @return int
	 */
	public int getIdCuenta()
	{
		return idCuenta;
	}

	/**
	 * Method 'setIdCuenta'
	 * 
	 * @param idCuenta
	 */
	public void setIdCuenta(int idCuenta)
	{
		this.idCuenta = idCuenta;
	}

	/**
	 * Method 'getNumEntidad'
	 * 
	 * @return int
	 */
	public int getNumEntidad()
	{
		return numEntidad;
	}

	/**
	 * Method 'setNumEntidad'
	 * 
	 * @param numEntidad
	 */
	public void setNumEntidad(int numEntidad)
	{
		this.numEntidad = numEntidad;
	}

	/**
	 * Method 'getNumSucursal'
	 * 
	 * @return int
	 */
	public int getNumSucursal()
	{
		return numSucursal;
	}

	/**
	 * Method 'setNumSucursal'
	 * 
	 * @param numSucursal
	 */
	public void setNumSucursal(int numSucursal)
	{
		this.numSucursal = numSucursal;
	}

	/**
	 * Method 'getNumDigitoControl'
	 * 
	 * @return int
	 */
	public int getNumDigitoControl()
	{
		return numDigitoControl;
	}

	/**
	 * Method 'setNumDigitoControl'
	 * 
	 * @param numDigitoControl
	 */
	public void setNumDigitoControl(int numDigitoControl)
	{
		this.numDigitoControl = numDigitoControl;
	}

	/**
	 * Method 'getNumCuenta'
	 * 
	 * @return long
	 */
	public long getNumCuenta()
	{
		return numCuenta;
	}

	/**
	 * Method 'setNumCuenta'
	 * 
	 * @param numCuenta
	 */
	public void setNumCuenta(long numCuenta)
	{
		this.numCuenta = numCuenta;
	}

	/**
	 * Method 'getSaldo'
	 * 
	 * @return float
	 */
	public float getSaldo()
	{
		return saldo;
	}

	/**
	 * Method 'setSaldo'
	 * 
	 * @param saldo
	 */
	public void setSaldo(float saldo)
	{
		this.saldo = saldo;
	}

	/**
	 * Method 'getFechaCreacion'
	 * 
	 * @return Date
	 */
	public Date getFechaCreacion()
	{
		return fechaCreacion;
	}

	/**
	 * Method 'setFechaCreacion'
	 * 
	 * @param fechaCreacion
	 */
	public void setFechaCreacion(Date fechaCreacion)
	{
		this.fechaCreacion = fechaCreacion;
	}

	/**
	 * Method 'getUsuarioIdUsuario'
	 * 
	 * @return int
	 */
	public int getUsuarioIdUsuario()
	{
		return usuarioIdUsuario;
	}

	/**
	 * Method 'setUsuarioIdUsuario'
	 * 
	 * @param usuarioIdUsuario
	 */
	public void setUsuarioIdUsuario(int usuarioIdUsuario)
	{
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CuentaEntidad)) {
			return false;
		}
		
		final CuentaEntidad _cast = (CuentaEntidad) _other;
		if (idCuenta != _cast.idCuenta) {
			return false;
		}
		
		if (numEntidad != _cast.numEntidad) {
			return false;
		}
		
		if (numSucursal != _cast.numSucursal) {
			return false;
		}
		
		if (numDigitoControl != _cast.numDigitoControl) {
			return false;
		}
		
		if (numCuenta != _cast.numCuenta) {
			return false;
		}
		
		if (saldo != _cast.saldo) {
			return false;
		}
		
		if (fechaCreacion == null ? _cast.fechaCreacion != fechaCreacion : !fechaCreacion.equals( _cast.fechaCreacion )) {
			return false;
		}
		
		if (usuarioIdUsuario != _cast.usuarioIdUsuario) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idCuenta;
		_hashCode = 29 * _hashCode + numEntidad;
		_hashCode = 29 * _hashCode + numSucursal;
		_hashCode = 29 * _hashCode + numDigitoControl;
		_hashCode = 29 * _hashCode + (int) (numCuenta ^ (numCuenta >>> 32));
		_hashCode = 29 * _hashCode + Float.floatToIntBits(saldo);
		if (fechaCreacion != null) {
			_hashCode = 29 * _hashCode + fechaCreacion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + usuarioIdUsuario;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CuentaEntidadPk
	 */
	public CuentaEntidadPk createPk()
	{
		return new CuentaEntidadPk(idCuenta);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.bankito.persistencia.dto.CuentaEntidad: " );
		ret.append( "idCuenta=" + idCuenta );
		ret.append( ", numEntidad=" + numEntidad );
		ret.append( ", numSucursal=" + numSucursal );
		ret.append( ", numDigitoControl=" + numDigitoControl );
		ret.append( ", numCuenta=" + numCuenta );
		ret.append( ", saldo=" + saldo );
		ret.append( ", fechaCreacion=" + fechaCreacion );
		ret.append( ", usuarioIdUsuario=" + usuarioIdUsuario );
		return ret.toString();
	}

}
