/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bankito.persistencia.dto;

import com.bankito.persistencia.dao.*;
import com.bankito.persistencia.factory.*;
import com.bankito.persistencia.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class MovimientoEntidad implements Serializable
{
	/** 
	 * This attribute maps to the column id_movimiento in the movimiento table.
	 */
	protected int idMovimiento;

	/** 
	 * This attribute maps to the column concepto in the movimiento table.
	 */
	protected String concepto;

	/** 
	 * This attribute maps to the column tipo in the movimiento table.
	 */
	protected String tipo;

	/** 
	 * This attribute maps to the column importe in the movimiento table.
	 */
	protected float importe;

	/** 
	 * This attribute maps to the column fecha_creacion in the movimiento table.
	 */
	protected Date fechaCreacion;

	/** 
	 * This attribute maps to the column cuenta_id_cuenta in the movimiento table.
	 */
	protected int cuentaIdCuenta;

	/**
	 * Method 'MovimientoEntidad'
	 * 
	 */
	public MovimientoEntidad()
	{
	}

	/**
	 * Method 'getIdMovimiento'
	 * 
	 * @return int
	 */
	public int getIdMovimiento()
	{
		return idMovimiento;
	}

	/**
	 * Method 'setIdMovimiento'
	 * 
	 * @param idMovimiento
	 */
	public void setIdMovimiento(int idMovimiento)
	{
		this.idMovimiento = idMovimiento;
	}

	/**
	 * Method 'getConcepto'
	 * 
	 * @return String
	 */
	public String getConcepto()
	{
		return concepto;
	}

	/**
	 * Method 'setConcepto'
	 * 
	 * @param concepto
	 */
	public void setConcepto(String concepto)
	{
		this.concepto = concepto;
	}

	/**
	 * Method 'getTipo'
	 * 
	 * @return String
	 */
	public String getTipo()
	{
            return tipo;
	}

	/**
	 * Method 'setTipo'
	 * 
	 * @param tipo
	 */
	public void setTipo(String tipo)
	{
		this.tipo = tipo;
	}

	/**
	 * Method 'getImporte'
	 * 
	 * @return float
	 */
	public float getImporte()
	{
		return importe;
	}

	/**
	 * Method 'setImporte'
	 * 
	 * @param importe
	 */
	public void setImporte(float importe)
	{
		this.importe = importe;
	}

	/**
	 * Method 'getFechaCreacion'
	 * 
	 * @return Date
	 */
	public Date getFechaCreacion()
	{
		return fechaCreacion;
	}

	/**
	 * Method 'setFechaCreacion'
	 * 
	 * @param fechaCreacion
	 */
	public void setFechaCreacion(Date fechaCreacion)
	{
		this.fechaCreacion = fechaCreacion;
	}

	/**
	 * Method 'getCuentaIdCuenta'
	 * 
	 * @return int
	 */
	public int getCuentaIdCuenta()
	{
		return cuentaIdCuenta;
	}

	/**
	 * Method 'setCuentaIdCuenta'
	 * 
	 * @param cuentaIdCuenta
	 */
	public void setCuentaIdCuenta(int cuentaIdCuenta)
	{
		this.cuentaIdCuenta = cuentaIdCuenta;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MovimientoEntidad)) {
			return false;
		}
		
		final MovimientoEntidad _cast = (MovimientoEntidad) _other;
		if (idMovimiento != _cast.idMovimiento) {
			return false;
		}
		
		if (concepto == null ? _cast.concepto != concepto : !concepto.equals( _cast.concepto )) {
			return false;
		}
		
		if (tipo == null ? _cast.tipo != tipo : !tipo.equals( _cast.tipo )) {
			return false;
		}
		
		if (importe != _cast.importe) {
			return false;
		}
		
		if (fechaCreacion == null ? _cast.fechaCreacion != fechaCreacion : !fechaCreacion.equals( _cast.fechaCreacion )) {
			return false;
		}
		
		if (cuentaIdCuenta != _cast.cuentaIdCuenta) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idMovimiento;
		if (concepto != null) {
			_hashCode = 29 * _hashCode + concepto.hashCode();
		}
		
		if (tipo != null) {
			_hashCode = 29 * _hashCode + tipo.hashCode();
		}
		
		_hashCode = 29 * _hashCode + Float.floatToIntBits(importe);
		if (fechaCreacion != null) {
			_hashCode = 29 * _hashCode + fechaCreacion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + cuentaIdCuenta;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MovimientoEntidadPk
	 */
	public MovimientoEntidadPk createPk()
	{
		return new MovimientoEntidadPk(idMovimiento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.bankito.persistencia.dto.MovimientoEntidad: " );
		ret.append( "idMovimiento=" + idMovimiento );
		ret.append( ", concepto=" + concepto );
		ret.append( ", tipo=" + tipo );
		ret.append( ", importe=" + importe );
		ret.append( ", fechaCreacion=" + fechaCreacion );
		ret.append( ", cuentaIdCuenta=" + cuentaIdCuenta );
		return ret.toString();
	}

}
