/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bankito.persistencia.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the operacion table.
 */
public class OperacionEntidadPk implements Serializable
{
	protected int idOperacion;

	/** 
	 * This attribute represents whether the primitive attribute idOperacion is null.
	 */
	protected boolean idOperacionNull;

	/** 
	 * Sets the value of idOperacion
	 */
	public void setIdOperacion(int idOperacion)
	{
		this.idOperacion = idOperacion;
	}

	/** 
	 * Gets the value of idOperacion
	 */
	public int getIdOperacion()
	{
		return idOperacion;
	}

	/**
	 * Method 'OperacionEntidadPk'
	 * 
	 */
	public OperacionEntidadPk()
	{
	}

	/**
	 * Method 'OperacionEntidadPk'
	 * 
	 * @param idOperacion
	 */
	public OperacionEntidadPk(final int idOperacion)
	{
		this.idOperacion = idOperacion;
	}

	/** 
	 * Sets the value of idOperacionNull
	 */
	public void setIdOperacionNull(boolean idOperacionNull)
	{
		this.idOperacionNull = idOperacionNull;
	}

	/** 
	 * Gets the value of idOperacionNull
	 */
	public boolean isIdOperacionNull()
	{
		return idOperacionNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof OperacionEntidadPk)) {
			return false;
		}
		
		final OperacionEntidadPk _cast = (OperacionEntidadPk) _other;
		if (idOperacion != _cast.idOperacion) {
			return false;
		}
		
		if (idOperacionNull != _cast.idOperacionNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idOperacion;
		_hashCode = 29 * _hashCode + (idOperacionNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.bankito.persistencia.dto.OperacionEntidadPk: " );
		ret.append( "idOperacion=" + idOperacion );
		return ret.toString();
	}

}
