/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bankito.persistencia.dto;

import java.io.Serializable;

public class OperacionEntidad implements Serializable
{
	/** 
	 * This attribute maps to the column id_operacion in the operacion table.
	 */
	protected int idOperacion;

	/** 
	 * This attribute represents whether the attribute idOperacion has been modified since being read from the database.
	 */
	protected boolean idOperacionModified = false;

	/** 
	 * This attribute maps to the column nombre_corto in the operacion table.
	 */
	protected String nombreCorto;

	/** 
	 * This attribute represents whether the attribute nombreCorto has been modified since being read from the database.
	 */
	protected boolean nombreCortoModified = false;

	/** 
	 * This attribute maps to the column nombre in the operacion table.
	 */
	protected String nombre;

	/** 
	 * This attribute represents whether the attribute nombre has been modified since being read from the database.
	 */
	protected boolean nombreModified = false;

	/** 
	 * This attribute maps to the column descripcion in the operacion table.
	 */
	protected String descripcion;

	/** 
	 * This attribute represents whether the attribute descripcion has been modified since being read from the database.
	 */
	protected boolean descripcionModified = false;

	/**
	 * Method 'OperacionEntidad'
	 * 
	 */
	public OperacionEntidad()
	{
	}

	/**
	 * Method 'getIdOperacion'
	 * 
	 * @return int
	 */
	public int getIdOperacion()
	{
		return idOperacion;
	}

	/**
	 * Method 'setIdOperacion'
	 * 
	 * @param idOperacion
	 */
	public void setIdOperacion(int idOperacion)
	{
		this.idOperacion = idOperacion;
		this.idOperacionModified = true;
	}

	/** 
	 * Sets the value of idOperacionModified
	 */
	public void setIdOperacionModified(boolean idOperacionModified)
	{
		this.idOperacionModified = idOperacionModified;
	}

	/** 
	 * Gets the value of idOperacionModified
	 */
	public boolean isIdOperacionModified()
	{
		return idOperacionModified;
	}

	/**
	 * Method 'getNombreCorto'
	 * 
	 * @return String
	 */
	public String getNombreCorto()
	{
		return nombreCorto;
	}

	/**
	 * Method 'setNombreCorto'
	 * 
	 * @param nombreCorto
	 */
	public void setNombreCorto(String nombreCorto)
	{
		this.nombreCorto = nombreCorto;
		this.nombreCortoModified = true;
	}

	/** 
	 * Sets the value of nombreCortoModified
	 */
	public void setNombreCortoModified(boolean nombreCortoModified)
	{
		this.nombreCortoModified = nombreCortoModified;
	}

	/** 
	 * Gets the value of nombreCortoModified
	 */
	public boolean isNombreCortoModified()
	{
		return nombreCortoModified;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
		this.nombreModified = true;
	}

	/** 
	 * Sets the value of nombreModified
	 */
	public void setNombreModified(boolean nombreModified)
	{
		this.nombreModified = nombreModified;
	}

	/** 
	 * Gets the value of nombreModified
	 */
	public boolean isNombreModified()
	{
		return nombreModified;
	}

	/**
	 * Method 'getDescripcion'
	 * 
	 * @return String
	 */
	public String getDescripcion()
	{
		return descripcion;
	}

	/**
	 * Method 'setDescripcion'
	 * 
	 * @param descripcion
	 */
	public void setDescripcion(String descripcion)
	{
		this.descripcion = descripcion;
		this.descripcionModified = true;
	}

	/** 
	 * Sets the value of descripcionModified
	 */
	public void setDescripcionModified(boolean descripcionModified)
	{
		this.descripcionModified = descripcionModified;
	}

	/** 
	 * Gets the value of descripcionModified
	 */
	public boolean isDescripcionModified()
	{
		return descripcionModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof OperacionEntidad)) {
			return false;
		}
		
		final OperacionEntidad _cast = (OperacionEntidad) _other;
		if (idOperacion != _cast.idOperacion) {
			return false;
		}
		
		if (idOperacionModified != _cast.idOperacionModified) {
			return false;
		}
		
		if (nombreCorto == null ? _cast.nombreCorto != nombreCorto : !nombreCorto.equals( _cast.nombreCorto )) {
			return false;
		}
		
		if (nombreCortoModified != _cast.nombreCortoModified) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (nombreModified != _cast.nombreModified) {
			return false;
		}
		
		if (descripcion == null ? _cast.descripcion != descripcion : !descripcion.equals( _cast.descripcion )) {
			return false;
		}
		
		if (descripcionModified != _cast.descripcionModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idOperacion;
		_hashCode = 29 * _hashCode + (idOperacionModified ? 1 : 0);
		if (nombreCorto != null) {
			_hashCode = 29 * _hashCode + nombreCorto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nombreCortoModified ? 1 : 0);
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nombreModified ? 1 : 0);
		if (descripcion != null) {
			_hashCode = 29 * _hashCode + descripcion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (descripcionModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return OperacionEntidadPk
	 */
	public OperacionEntidadPk createPk()
	{
		return new OperacionEntidadPk(idOperacion);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.bankito.persistencia.dto.OperacionEntidad: " );
		ret.append( "idOperacion=" + idOperacion );
		ret.append( ", nombreCorto=" + nombreCorto );
		ret.append( ", nombre=" + nombre );
		ret.append( ", descripcion=" + descripcion );
		return ret.toString();
	}

}
