/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bankito.persistencia.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the perfil_usuario table.
 */
public class PerfilUsuarioEntidadPk implements Serializable
{
	protected int idPerfilUsuario;

	/** 
	 * This attribute represents whether the primitive attribute idPerfilUsuario is null.
	 */
	protected boolean idPerfilUsuarioNull;

	/** 
	 * Sets the value of idPerfilUsuario
	 */
	public void setIdPerfilUsuario(int idPerfilUsuario)
	{
		this.idPerfilUsuario = idPerfilUsuario;
	}

	/** 
	 * Gets the value of idPerfilUsuario
	 */
	public int getIdPerfilUsuario()
	{
		return idPerfilUsuario;
	}

	/**
	 * Method 'PerfilUsuarioEntidadPk'
	 * 
	 */
	public PerfilUsuarioEntidadPk()
	{
	}

	/**
	 * Method 'PerfilUsuarioEntidadPk'
	 * 
	 * @param idPerfilUsuario
	 */
	public PerfilUsuarioEntidadPk(final int idPerfilUsuario)
	{
		this.idPerfilUsuario = idPerfilUsuario;
	}

	/** 
	 * Sets the value of idPerfilUsuarioNull
	 */
	public void setIdPerfilUsuarioNull(boolean idPerfilUsuarioNull)
	{
		this.idPerfilUsuarioNull = idPerfilUsuarioNull;
	}

	/** 
	 * Gets the value of idPerfilUsuarioNull
	 */
	public boolean isIdPerfilUsuarioNull()
	{
		return idPerfilUsuarioNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PerfilUsuarioEntidadPk)) {
			return false;
		}
		
		final PerfilUsuarioEntidadPk _cast = (PerfilUsuarioEntidadPk) _other;
		if (idPerfilUsuario != _cast.idPerfilUsuario) {
			return false;
		}
		
		if (idPerfilUsuarioNull != _cast.idPerfilUsuarioNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idPerfilUsuario;
		_hashCode = 29 * _hashCode + (idPerfilUsuarioNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.bankito.persistencia.dto.PerfilUsuarioEntidadPk: " );
		ret.append( "idPerfilUsuario=" + idPerfilUsuario );
		return ret.toString();
	}

}
