/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bankito.persistencia.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the sesion table.
 */
public class SesionEntidadPk implements Serializable
{
	protected int idSesion;

	/** 
	 * This attribute represents whether the primitive attribute idSesion is null.
	 */
	protected boolean idSesionNull;

	/** 
	 * Sets the value of idSesion
	 */
	public void setIdSesion(int idSesion)
	{
		this.idSesion = idSesion;
	}

	/** 
	 * Gets the value of idSesion
	 */
	public int getIdSesion()
	{
		return idSesion;
	}

	/**
	 * Method 'SesionEntidadPk'
	 * 
	 */
	public SesionEntidadPk()
	{
	}

	/**
	 * Method 'SesionEntidadPk'
	 * 
	 * @param idSesion
	 */
	public SesionEntidadPk(final int idSesion)
	{
		this.idSesion = idSesion;
	}

	/** 
	 * Sets the value of idSesionNull
	 */
	public void setIdSesionNull(boolean idSesionNull)
	{
		this.idSesionNull = idSesionNull;
	}

	/** 
	 * Gets the value of idSesionNull
	 */
	public boolean isIdSesionNull()
	{
		return idSesionNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof SesionEntidadPk)) {
			return false;
		}
		
		final SesionEntidadPk _cast = (SesionEntidadPk) _other;
		if (idSesion != _cast.idSesion) {
			return false;
		}
		
		if (idSesionNull != _cast.idSesionNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idSesion;
		_hashCode = 29 * _hashCode + (idSesionNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.bankito.persistencia.dto.SesionEntidadPk: " );
		ret.append( "idSesion=" + idSesion );
		return ret.toString();
	}

}
