/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bankito.persistencia.dto;

import com.bankito.persistencia.dao.*;
import com.bankito.persistencia.factory.*;
import com.bankito.persistencia.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class UsuarioEntidad implements Serializable
{
	/** 
	 * This attribute maps to the column id_usuario in the usuario table.
	 */
	protected int idUsuario;

	/** 
	 * This attribute represents whether the attribute idUsuario has been modified since being read from the database.
	 */
	protected boolean idUsuarioModified = false;

	/** 
	 * This attribute maps to the column nombre in the usuario table.
	 */
	protected String nombre;

	/** 
	 * This attribute represents whether the attribute nombre has been modified since being read from the database.
	 */
	protected boolean nombreModified = false;

	/** 
	 * This attribute maps to the column password in the usuario table.
	 */
	protected String password;

	/** 
	 * This attribute represents whether the attribute password has been modified since being read from the database.
	 */
	protected boolean passwordModified = false;

	/** 
	 * This attribute maps to the column fecha_creacion in the usuario table.
	 */
	protected Date fechaCreacion;

	/** 
	 * This attribute represents whether the attribute fechaCreacion has been modified since being read from the database.
	 */
	protected boolean fechaCreacionModified = false;

	/** 
	 * This attribute maps to the column fecha_modificacion in the usuario table.
	 */
	protected Date fechaModificacion;

	/** 
	 * This attribute represents whether the attribute fechaModificacion has been modified since being read from the database.
	 */
	protected boolean fechaModificacionModified = false;

	/** 
	 * This attribute maps to the column perfil_usuario_id_perfil in the usuario table.
	 */
	protected int perfilUsuarioIdPerfil;

	/** 
	 * This attribute represents whether the primitive attribute perfilUsuarioIdPerfil is null.
	 */
	protected boolean perfilUsuarioIdPerfilNull = true;

	/** 
	 * This attribute represents whether the attribute perfilUsuarioIdPerfil has been modified since being read from the database.
	 */
	protected boolean perfilUsuarioIdPerfilModified = false;

	/**
	 * Method 'UsuarioEntidad'
	 * 
	 */
	public UsuarioEntidad()
	{
	}

	/**
	 * Method 'getIdUsuario'
	 * 
	 * @return int
	 */
	public int getIdUsuario()
	{
		return idUsuario;
	}

	/**
	 * Method 'setIdUsuario'
	 * 
	 * @param idUsuario
	 */
	public void setIdUsuario(int idUsuario)
	{
		this.idUsuario = idUsuario;
		this.idUsuarioModified = true;
	}

	/** 
	 * Sets the value of idUsuarioModified
	 */
	public void setIdUsuarioModified(boolean idUsuarioModified)
	{
		this.idUsuarioModified = idUsuarioModified;
	}

	/** 
	 * Gets the value of idUsuarioModified
	 */
	public boolean isIdUsuarioModified()
	{
		return idUsuarioModified;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
		this.nombreModified = true;
	}

	/** 
	 * Sets the value of nombreModified
	 */
	public void setNombreModified(boolean nombreModified)
	{
		this.nombreModified = nombreModified;
	}

	/** 
	 * Gets the value of nombreModified
	 */
	public boolean isNombreModified()
	{
		return nombreModified;
	}

	/**
	 * Method 'getPassword'
	 * 
	 * @return String
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * Method 'setPassword'
	 * 
	 * @param password
	 */
	public void setPassword(String password)
	{
		this.password = password;
		this.passwordModified = true;
	}

	/** 
	 * Sets the value of passwordModified
	 */
	public void setPasswordModified(boolean passwordModified)
	{
		this.passwordModified = passwordModified;
	}

	/** 
	 * Gets the value of passwordModified
	 */
	public boolean isPasswordModified()
	{
		return passwordModified;
	}

	/**
	 * Method 'getFechaCreacion'
	 * 
	 * @return Date
	 */
	public Date getFechaCreacion()
	{
		return fechaCreacion;
	}

	/**
	 * Method 'setFechaCreacion'
	 * 
	 * @param fechaCreacion
	 */
	public void setFechaCreacion(Date fechaCreacion)
	{
		this.fechaCreacion = fechaCreacion;
		this.fechaCreacionModified = true;
	}

	/** 
	 * Sets the value of fechaCreacionModified
	 */
	public void setFechaCreacionModified(boolean fechaCreacionModified)
	{
		this.fechaCreacionModified = fechaCreacionModified;
	}

	/** 
	 * Gets the value of fechaCreacionModified
	 */
	public boolean isFechaCreacionModified()
	{
		return fechaCreacionModified;
	}

	/**
	 * Method 'getFechaModificacion'
	 * 
	 * @return Date
	 */
	public Date getFechaModificacion()
	{
		return fechaModificacion;
	}

	/**
	 * Method 'setFechaModificacion'
	 * 
	 * @param fechaModificacion
	 */
	public void setFechaModificacion(Date fechaModificacion)
	{
		this.fechaModificacion = fechaModificacion;
		this.fechaModificacionModified = true;
	}

	/** 
	 * Sets the value of fechaModificacionModified
	 */
	public void setFechaModificacionModified(boolean fechaModificacionModified)
	{
		this.fechaModificacionModified = fechaModificacionModified;
	}

	/** 
	 * Gets the value of fechaModificacionModified
	 */
	public boolean isFechaModificacionModified()
	{
		return fechaModificacionModified;
	}

	/**
	 * Method 'getPerfilUsuarioIdPerfil'
	 * 
	 * @return int
	 */
	public int getPerfilUsuarioIdPerfil()
	{
		return perfilUsuarioIdPerfil;
	}

	/**
	 * Method 'setPerfilUsuarioIdPerfil'
	 * 
	 * @param perfilUsuarioIdPerfil
	 */
	public void setPerfilUsuarioIdPerfil(int perfilUsuarioIdPerfil)
	{
		this.perfilUsuarioIdPerfil = perfilUsuarioIdPerfil;
		this.perfilUsuarioIdPerfilNull = false;
		this.perfilUsuarioIdPerfilModified = true;
	}

	/**
	 * Method 'setPerfilUsuarioIdPerfilNull'
	 * 
	 * @param value
	 */
	public void setPerfilUsuarioIdPerfilNull(boolean value)
	{
		this.perfilUsuarioIdPerfilNull = value;
		this.perfilUsuarioIdPerfilModified = true;
	}

	/**
	 * Method 'isPerfilUsuarioIdPerfilNull'
	 * 
	 * @return boolean
	 */
	public boolean isPerfilUsuarioIdPerfilNull()
	{
		return perfilUsuarioIdPerfilNull;
	}

	/** 
	 * Sets the value of perfilUsuarioIdPerfilModified
	 */
	public void setPerfilUsuarioIdPerfilModified(boolean perfilUsuarioIdPerfilModified)
	{
		this.perfilUsuarioIdPerfilModified = perfilUsuarioIdPerfilModified;
	}

	/** 
	 * Gets the value of perfilUsuarioIdPerfilModified
	 */
	public boolean isPerfilUsuarioIdPerfilModified()
	{
		return perfilUsuarioIdPerfilModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof UsuarioEntidad)) {
			return false;
		}
		
		final UsuarioEntidad _cast = (UsuarioEntidad) _other;
		if (idUsuario != _cast.idUsuario) {
			return false;
		}
		
		if (idUsuarioModified != _cast.idUsuarioModified) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (nombreModified != _cast.nombreModified) {
			return false;
		}
		
		if (password == null ? _cast.password != password : !password.equals( _cast.password )) {
			return false;
		}
		
		if (passwordModified != _cast.passwordModified) {
			return false;
		}
		
		if (fechaCreacion == null ? _cast.fechaCreacion != fechaCreacion : !fechaCreacion.equals( _cast.fechaCreacion )) {
			return false;
		}
		
		if (fechaCreacionModified != _cast.fechaCreacionModified) {
			return false;
		}
		
		if (fechaModificacion == null ? _cast.fechaModificacion != fechaModificacion : !fechaModificacion.equals( _cast.fechaModificacion )) {
			return false;
		}
		
		if (fechaModificacionModified != _cast.fechaModificacionModified) {
			return false;
		}
		
		if (perfilUsuarioIdPerfil != _cast.perfilUsuarioIdPerfil) {
			return false;
		}
		
		if (perfilUsuarioIdPerfilNull != _cast.perfilUsuarioIdPerfilNull) {
			return false;
		}
		
		if (perfilUsuarioIdPerfilModified != _cast.perfilUsuarioIdPerfilModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idUsuario;
		_hashCode = 29 * _hashCode + (idUsuarioModified ? 1 : 0);
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nombreModified ? 1 : 0);
		if (password != null) {
			_hashCode = 29 * _hashCode + password.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (passwordModified ? 1 : 0);
		if (fechaCreacion != null) {
			_hashCode = 29 * _hashCode + fechaCreacion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (fechaCreacionModified ? 1 : 0);
		if (fechaModificacion != null) {
			_hashCode = 29 * _hashCode + fechaModificacion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (fechaModificacionModified ? 1 : 0);
		_hashCode = 29 * _hashCode + perfilUsuarioIdPerfil;
		_hashCode = 29 * _hashCode + (perfilUsuarioIdPerfilNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (perfilUsuarioIdPerfilModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return UsuarioEntidadPk
	 */
	public UsuarioEntidadPk createPk()
	{
		return new UsuarioEntidadPk(idUsuario);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.bankito.persistencia.dto.UsuarioEntidad: " );
		ret.append( "idUsuario=" + idUsuario );
		ret.append( ", nombre=" + nombre );
		ret.append( ", password=" + password );
		ret.append( ", fechaCreacion=" + fechaCreacion );
		ret.append( ", fechaModificacion=" + fechaModificacion );
		ret.append( ", perfilUsuarioIdPerfil=" + perfilUsuarioIdPerfil );
		return ret.toString();
	}

}
