/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bankito.persistencia.dto;

import com.bankito.dominio.Usuario;
import com.bankito.persistencia.dao.*;
import com.bankito.persistencia.factory.*;
import com.bankito.persistencia.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class UsuarioEntidad implements Serializable
{
	/** 
	 * This attribute maps to the column id_usuario in the usuario table.
	 */
	protected int idUsuario;

	/** 
	 * This attribute maps to the column nombre in the usuario table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column password in the usuario table.
	 */
	protected String password;

	/** 
	 * This attribute maps to the column fecha_creacion in the usuario table.
	 */
	protected Date fechaCreacion;

	/** 
	 * This attribute maps to the column fecha_modificacion in the usuario table.
	 */
	protected Date fechaModificacion;

	/**
	 * Method 'UsuarioEntidad'
	 * 
	 */
	public UsuarioEntidad()
	{
	}

	/**
	 * Method 'getIdUsuario'
	 * 
	 * @return int
	 */
	public int getIdUsuario()
	{
		return idUsuario;
	}

	/**
	 * Method 'setIdUsuario'
	 * 
	 * @param idUsuario
	 */
	public void setIdUsuario(int idUsuario)
	{
		this.idUsuario = idUsuario;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getPassword'
	 * 
	 * @return String
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * Method 'setPassword'
	 * 
	 * @param password
	 */
	public void setPassword(String password)
	{
		this.password = password;
	}

	/**
	 * Method 'getFechaCreacion'
	 * 
	 * @return Date
	 */
	public Date getFechaCreacion()
	{
		return fechaCreacion;
	}

	/**
	 * Method 'setFechaCreacion'
	 * 
	 * @param fechaCreacion
	 */
	public void setFechaCreacion(Date fechaCreacion)
	{
		this.fechaCreacion = fechaCreacion;
	}

	/**
	 * Method 'getFechaModificacion'
	 * 
	 * @return Date
	 */
	public Date getFechaModificacion()
	{
		return fechaModificacion;
	}

	/**
	 * Method 'setFechaModificacion'
	 * 
	 * @param fechaModificacion
	 */
	public void setFechaModificacion(Date fechaModificacion)
	{
		this.fechaModificacion = fechaModificacion;
	}

        
	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof UsuarioEntidad)) {
			return false;
		}
		
		final UsuarioEntidad _cast = (UsuarioEntidad) _other;
		if (idUsuario != _cast.idUsuario) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (password == null ? _cast.password != password : !password.equals( _cast.password )) {
			return false;
		}
		
		if (fechaCreacion == null ? _cast.fechaCreacion != fechaCreacion : !fechaCreacion.equals( _cast.fechaCreacion )) {
			return false;
		}
		
		if (fechaModificacion == null ? _cast.fechaModificacion != fechaModificacion : !fechaModificacion.equals( _cast.fechaModificacion )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idUsuario;
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		if (password != null) {
			_hashCode = 29 * _hashCode + password.hashCode();
		}
		
		if (fechaCreacion != null) {
			_hashCode = 29 * _hashCode + fechaCreacion.hashCode();
		}
		
		if (fechaModificacion != null) {
			_hashCode = 29 * _hashCode + fechaModificacion.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return UsuarioEntidadPk
	 */
	public UsuarioEntidadPk createPk()
	{
		return new UsuarioEntidadPk(idUsuario);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.bankito.persistencia.dto.UsuarioEntidad: " );
		ret.append( "idUsuario=" + idUsuario );
		ret.append( ", nombre=" + nombre );
		ret.append( ", password=" + password );
		ret.append( ", fechaCreacion=" + fechaCreacion );
		ret.append( ", fechaModificacion=" + fechaModificacion );
		return ret.toString();
	}

}
